apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  type: ClusterIP
  selector:
    app: canary
    # version: "1.0"  #commented to do canary deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80